#!/bin/sh
# Bootstrap the Mosquitto password and ACL files.
#
# Run once during initial broker setup. Creates an `admin` user with the
# password supplied via the ADMIN_PASSWORD env var and writes a minimal
# ACL file granting admin full access on all topics. Refuses to run if
# the password file already exists.
#
# Usage:
#   docker exec -e ADMIN_PASSWORD='your-strong-password' \
#       -it mosquitto sh /mosquitto/config/scripts/init_admin.sh
#
# After running, restart Mosquitto so it loads the new files:
#   docker compose restart mosquitto

set -eu

PASSWORD_FILE="/mosquitto/config/passwords"
ACL_FILE="/mosquitto/config/acl"

if [ -z "${ADMIN_PASSWORD:-}" ]; then
    echo "Error: ADMIN_PASSWORD env var must be set." >&2
    exit 1
fi

if [ -e "$PASSWORD_FILE" ]; then
    echo "Refusing to run: $PASSWORD_FILE already exists." >&2
    echo "Delete it manually if you really want to re-bootstrap." >&2
    exit 1
fi

# -c creates the file; -b reads the password as the next argument (non-interactive).
mosquitto_passwd -c -b "$PASSWORD_FILE" admin "$ADMIN_PASSWORD"

cat > "$ACL_FILE" <<'EOF'
# Mosquitto ACL — generated by init_admin.sh.
# Append per-device blocks via add_device.sh.

user admin
topic readwrite #
EOF

echo "Created $PASSWORD_FILE and $ACL_FILE."
echo "Admin user provisioned. Restart Mosquitto so the new files take effect:"
echo "  docker compose restart mosquitto"
